### ISSUE TITLE
Bug: Przerwa w harmonogramie

### ISSUE THREAD

**Issue by D-Mielewczyk** [groupplants/docs#13]
Harmonogram w naszej dokumentacji jest przechowywany w dwóch oddzielnych plikach `.jpg`. Powoduje to błąd w ui:

![Image](https://github.com/groupplants/docs/assets/55713797/c34fdaf2-160b-413a-a0c6-cb674859b0d3)

Fix: Scalić pliki `.jpg` i wstawić ścieżke do scalonego pliku do `docs/harmonogram.md`

**Comment by olaaaf** [comment]
heeej jak tam @Pro100wnick1

**Comment by D-Mielewczyk** [comment]
![Image](https://github.com/groupplants/docs/assets/55713797/e807bcd6-008d-4b13-8526-3e59b4070730)

powiedzmy ze zrobione
