### ISSUE TITLE
Dodanie "branch protection"

### ISSUE THREAD

**Issue by D-Mielewczyk** [groupplants/docs#14]
Wyszukaj i dodaj branch protection (zakaz commitowania do maina) do każdego repo.

**Comment by D-Mielewczyk** [comment]
Możliwe, że się nie da, ale zrób proszę research i popróboj (zweryfikuj czy serio się nie da, bo to ważne), 

Poszukaj też informacji o tym, czy możemy zapobiegać mergowaniu MR bez approve.

**Comment by Mihaau** [comment]
https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/managing-custom-repository-roles-for-an-organization
@D-Mielewczyk 
@olaaaf

**Comment by D-Mielewczyk** [comment]
Dobra dzięki za reaserch @Niviann jeszcze poklikałem i widzę, że się nie da. Stworzyłem nawet mergre request z włączonym "blokowaniem merge bez approve" i miałem tam informacje, że to zadzaiał tylko w github enterprise. 

Tej custom roli z dostępem nawet nie mogę Ci dać.
