### ISSUE TITLE
Dokumentacja techniczna

### ISSUE THREAD

**Issue by olaaaf** [groupplants/docs#18]
zawiera udokumentowane informacje dotyczące produktu, jego cech funkcjonalnych, parametrów technicznych, schematów blokowych, oprogramowania, wyników działania, zdjęć produktu itp.; o zakresie szczegółowym tego dokumentu decyduje opiekun w porozumieniu z klientem

**Comment by D-Mielewczyk** [comment]
Wydaje mi się że to jest po prostu https://groupplants.github.io/docs/

**Comment by olaaaf** [comment]
mozliwe..
