### ISSUE TITLE
Harmonogram

### ISSUE THREAD

**Issue by olaaaf** [groupplants/docs#19]
zawiera następujące informacje:

- harmonogram projektu w I semestrze z podziałem na główne etapy i wskazaniem terminów ich realizacji
- informacje dotyczące wskazania i opisania zadań i ról w projekcie (w kontekście etapów harmonogramu) oraz planowanego podziału zadań w zespole projektowym
- specyfikację wymagań określonych dla projektu, nałożonych przez opiekuna i klienta itp.

**Comment by D-Mielewczyk** [comment]
To jest już zrobione...

https://groupplants.github.io/docs/harmonogram/
