### ISSUE TITLE
Informacje o projekcie

### ISSUE THREAD

**Issue by olaaaf** [groupplants/docs#20]
dokument zawiera informacje o projekcie i wykonawcach, celu, temacie i zakresie projektu, wstępnie planowanym zakresie prac oraz uproszczoną analizę ryzyka

**Comment by D-Mielewczyk** [comment]
Duplicates #36

**Comment by olaaaf** [comment]
[PG_WETI_IoP_wer. 1.00.doc.zip](https://github.com/groupplants/docs/files/14029359/PG_WETI_IoP_wer.1.00.doc.zip)
